language: python
python:
  - "2.7"
env:
  - DJANGO=django==1.5
  - DJANGO=django==1.6b1
install:
  - pip install $DJANGO --use-mirrors
  - make travis
script: make test
notifications:
  irc: "irc.freenode.org#opps"
  on_success: "never"
