language: python
python:
  - "2.7"
services:
  - redis-server
env:
  - DJANGO=django==1.6
install:
  - pip install $DJANGO
  - python setup.py develop
script: make test
notifications:
  irc: "irc.freenode.org#opps"
  on_success: "never"
after_success:
  - coveralls
